name: Build Workflow
on:
  workflow_dispatch: # callable manually
  push:
    tags: # Build on tag creation (any)
      - '*'
jobs:
  test-n-lint:
    uses: ./.github/workflows/test-n-lint.yml
  build:
    name: Build the image
    runs-on: ubuntu-latest
    needs: [test-n-lint] # Requires "Test & Lint" workflow to succeed
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_PROJECT }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
